### ISSUE TITLE
채널에 관한 소개

### ISSUE THREAD

**Issue by kciter** [gongzza/vuekr-bot#1]
https://github.com/Leop0ld/vuekr-bot/issues/5
위 링크에서 넘어왔습니다.

9XD 슬렉에서는 누군가 가입했을때 채널에 대한 소개를 하더라구요 ㅎㅎ
뷰 슬렉도 사람이 많아짐에 따라서 채널 별 설명이 필요할 것 같습니다.
```
general
awesome
jobs
updates
question
news
```
우선은 이정도에 대해서 설명하면 좋을 것 같습니다.
혹시 작업해주시면 매우 감사드리지만 바쁘시다면 추후에 제가 작업해보겠습니다. :)

**Comment by dhlim-dev** [comment]
좋은 기능인 것 같습니다.

채널별로 간략하게 한줄정도의 소개글이 나오는 정도인가요??

**Comment by kciter** [comment]
넵 맞습니다 :)
`general` 채널에서는 나머지 채널들도 같이 소개하면 좋을 것 같아요.

**Comment by ChangJoo-Park** [comment]
추가 의견입니다
처음 general에 들어오시면 꼭 보아야할 사이트 목록(한글화 된 가이드 및 페이스북 등)에 대한 설명을 알려주면 좋을 것 같습니다.

**Comment by dhlim-dev** [comment]
그러면 #general에는 환영 메시지만 보여주고 다이렉트 메시지로 위에서 제시된 내용들을 보여주는건 어떨까요?

**Comment by ChangJoo-Park** [comment]
괜찮을거 같아요

**Comment by dhlim-dev** [comment]
[hubot-slack](https://github.com/slackapi/hubot-slack) 버전을 올리니까 쉽게 되네요.. ~또 삽질만 열심이..~
채널 소개와 추천 사이트 목록이 정리되는 대로 업데이트 하겠습니다.

**Comment by dhlim-dev** [comment]
#general채널 입장 시 아래와 같은 메시지가 DM으로 전송됩니다.
```
*추천 사이트*
Vue.js 한국어 - http://kr.vuejs.org/
Vue.js 한국어 사용자 모임 - https://vuejs-kr.github.io/
영어 강의 동영상 - https://laracasts.com/series/learn-vue-2-step-by-step/
Vue.js 프로젝트 시작을 위한 CLI입니다. - https://github.com/vuejs-kr/vue-cli/
Vue.js 개발환경 - https://vuejs-kr.github.io/update/2016/12/20/starting-vue/
vue-router 한국어 - https://router.vuejs.org/kr/
vuex 한국어 - https://vuex.vuejs.org/kr/

*채널설명*
#bot_playground - 봇 테스트 채널
#general - 잡담/질문/드립 모든게 허용되는 채널
#awesome - 유용한 링크를 소개하는 채널
#jobs - 구인구직 관련 채널
#updates - Vue.js 한국어 사용자 git 변경 내역을 알려주는 채널
#question - 질문 채널
#news - Vue.js 관련 소식을 보여주는 채널
#semantic-ui - semantic-ui를 잘 사용하고 싶은 사용자 채널
#random - 사실상 사용하지 않는 채널
```
위 내용은 [welcome.json](https://github.com/gongzza/vuekr-bot/blob/master/welcome.json)에서 수정할 수 있습니다.
